#ifndef PLATFORM_MSG_H_
#define PLATFORM_MSG_H_

#define COMMS_MSG_ADDRESSING_SIZE 0
#define COMMS_MSG_HEADER_SIZE 0
#define COMMS_MSG_PAYLOAD_SIZE 128
#define COMMS_MSG_FOOTER_SIZE 0
#define COMMS_MSG_METADATA_SIZE 0

#endif//PLATFORM_MSG_H_